"""roundup queue tables and basket publish tracking

Cola de fondo para "generar artículo de una cesta" cuando alguna de sus
fichas todavía no está publicada -- ver backend/app/services/roundup_queue.py.
roundup_queue guarda el trabajo (tema, post_id opcional para actualizar
en vez de crear, basket_id de origen); roundup_queue_place fija los
place_ids que debe esperar antes de escribir el artículo. Al crear el
trabajo se encola una sola vez (no en cada tick) lo que falte publicar en
publication_queue, para no reintentar sin límite una ficha que ya falló.

Las columnas published_* en basket marcan cuándo una cesta ya produjo un
artículo -- roundup_queue las rellena al completar un trabajo con
basket_id, y el panel usa published_post_id para no dejar generar un
segundo artículo desde la misma cesta.

Revision ID: 0ddb0e4bd027
Revises: 5aa2afba8ad1
Create Date: 2026-07-31 21:17:00.017350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddb0e4bd027'
down_revision: Union[str, Sequence[str], None] = '5aa2afba8ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roundup_queue_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), server_default=sa.text('(15)'), nullable=False),
    sa.Column('next_run_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_roundup_queue_control_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roundup_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tema', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result_post_id', sa.Integer(), nullable=True),
    sa.Column('result_url', sa.Text(), nullable=True),
    sa.Column('result_title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='ck_roundup_queue_status'),
    sa.ForeignKeyConstraint(['basket_id'], ['basket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roundup_queue_place',
    sa.Column('roundup_queue_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['roundup_queue_id'], ['roundup_queue.id'], ),
    sa.PrimaryKeyConstraint('roundup_queue_id', 'place_id')
    )
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('published_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('published_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.Integer(), nullable=True))

    # ### end Alembic commands ###
    op.execute(
        """
        INSERT OR IGNORE INTO roundup_queue_control
            (id, active, interval_seconds, next_run_at, updated_at)
        VALUES (1, 0, 15, NULL, strftime('%s', 'now'))
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.drop_column('published_at')
        batch_op.drop_column('published_title')
        batch_op.drop_column('published_url')
        batch_op.drop_column('published_post_id')

    op.drop_table('roundup_queue_place')
    op.drop_table('roundup_queue')
    op.drop_table('roundup_queue_control')
    # ### end Alembic commands ###
