"""basket tables

Cestas con nombre para agrupar fichas de cara a escribir artículos de
resumen (roundups) más tarde -- ver backend/app/api/baskets.py. `basket`
guarda el nombre (por defecto, el término de la búsqueda de Maps que
originó la cesta); `basket_place` es la relación N:M con `place`, con
INSERT OR IGNORE a nivel de aplicación para que añadir dos veces el mismo
sitio sea un no-op.

Revision ID: 5aa2afba8ad1
Revises: eda8f706cf70
Create Date: 2026-07-31 19:12:03.832250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa2afba8ad1'
down_revision: Union[str, Sequence[str], None] = 'eda8f706cf70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_place',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Text(), nullable=False),
    sa.Column('added_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['basket.id'], ),
    sa.PrimaryKeyConstraint('basket_id', 'place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_place')
    op.drop_table('basket')
    # ### end Alembic commands ###
