"""seed tables and google places usage

Añade las tablas del pipeline de siembra masiva por ciudad (Fase 3-4 del
roadmap, generalizable a sector y país -- ver
docs/inventories/2026-07-30-seed-queue.md): seed_location (ciudades
semilla, ampliable sin tocar código), seed_queue/seed_queue_control (misma
arquitectura que publication_queue/repair_queue) y google_places_usage
(tracking de coste, mismo patrón que openai_usage). Inserta también la
fila de control y las 102 ciudades semilla iniciales (52 capitales de
provincia españolas + 50 ciudades principales de EEUU), igual que hace
init_db() en instalaciones nuevas -- INSERT OR IGNORE, no falla si ya
estaban insertadas.

Revision ID: eda8f706cf70
Revises: ef082d3b0c89
Create Date: 2026-07-30 09:54:27.932839

"""
import os
import sys
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Permite importar app.data.seed_locations al correr `alembic` desde
# backend/ sin instalar el paquete `app` (mismo patrón que alembic/env.py).
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from app.data.seed_locations import SEED_CITIES_BY_COUNTRY, seed_locations_for  # noqa: E402

# Backfill histórico: todas las ciudades semilla que este código conoce,
# de todos los países, no solo el configurado para esta instalación
# (init_db() sí se limita a DIRECTORY_COUNTRY_CODE, pero esta migración
# reproduce el estado que tenía la base de datos cuando se creó, antes
# de que existiera ese filtro).
SEED_LOCATIONS = seed_locations_for(list(SEED_CITIES_BY_COUNTRY.keys()))


# revision identifiers, used by Alembic.
revision: str = 'eda8f706cf70'
down_revision: Union[str, Sequence[str], None] = 'ef082d3b0c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('tier', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('active', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("tier IN ('capital', 'manual')", name='ck_seed_location_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'name', 'region')
    )
    op.get_bind().execute(
        sa.text(
            """
            INSERT OR IGNORE INTO seed_location
                (country_code, name, region, tier, active, created_at)
            VALUES (:country_code, :name, :region, :tier, 1, strftime('%s', 'now'))
            """
        ),
        [
            {"country_code": cc, "name": name, "region": region, "tier": tier}
            for cc, name, region, tier in SEED_LOCATIONS
        ],
    )
    op.create_table('seed_queue_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), server_default=sa.text('(300)'), nullable=False),
    sa.Column('next_run_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_seed_queue_control_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        """
        INSERT OR IGNORE INTO seed_queue_control
            (id, active, interval_seconds, next_run_at, updated_at)
        VALUES (1, 0, 300, NULL, strftime('%s', 'now'))
        """
    )
    op.create_table('google_places_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('endpoint_version', sa.Text(), nullable=False),
    sa.Column('field_mask', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('seed_location_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('directory_search_term', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('place_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['seed_location_id'], ['seed_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_places_usage', schema=None) as batch_op:
        batch_op.create_index('idx_google_places_usage_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_google_places_usage_seed_location_id', ['seed_location_id'], unique=False)

    op.create_table('seed_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seed_location_id', sa.Integer(), nullable=False),
    sa.Column('search_term', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('places_found', sa.Integer(), nullable=True),
    sa.Column('places_saved', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seed_location_id'], ['seed_location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_location_id', 'search_term')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_queue')
    with op.batch_alter_table('google_places_usage', schema=None) as batch_op:
        batch_op.drop_index('idx_google_places_usage_seed_location_id')
        batch_op.drop_index('idx_google_places_usage_created_at')

    op.drop_table('google_places_usage')
    op.drop_table('seed_queue_control')
    op.drop_table('seed_location')
    # ### end Alembic commands ###
